[package]
name = "ministo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bus = "2.4.1"
clap = { version = "4.4.18", features = ["derive"] }
hex = { version = "0.4.3", features = ["serde"] }
randomx-rs = { git = "https://github.com/Cuprate/randomx-rs.git", version = "1.3.0" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
