name: Build Ministo with Minimal GLIBC (unixgeek image)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Ministo repository
        run: git clone https://github.com/emjomi/ministo.git

      - name: Build Ministo with unixgeek rust-min-libc Docker image
        run: |
          cd ministo
          docker run --rm \
            --volume "$PWD":/src \
            --user "$(id -u):$(id -g)" \
            unixgeek/rust-min-libc-target build --release

      - name: List build artifacts
        run: ls -lh ministo/target/release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ministo-release
          path: ministo/target/release/
