name: Build Ministo with Minimal GLIBC

on:
  workflow_dispatch:  # manual trigger, can also add 'schedule' or 'push'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Ministo repository
        run: |
          git clone https://github.com/emjomi/ministo.git
          cd ministo
          docker run --rm \
            --volume "$PWD":/src \
            --user "$(id -u):$(id -g)" \
            ghcr.io/manticoresoftware/rust-min-libc build --release

      - name: List built files
        run: ls -lh ministo/target/release
