name: Build Ministo with unixgeek rust-min-libc-target Dockerfile

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ministo repository
        run: git clone https://github.com/emjomi/ministo.git

      - name: Checkout unixgeek rust-min-libc-target repo
        run: git clone https://github.com/unixgeek/docker-rust-min-libc-target.git

      - name: Build rust-min-libc-target Docker image
        run: |
          docker build -t rust-min-libc-target ./docker-rust-min-libc-target

      - name: Build Ministo with rust-min-libc-target image
        run: |
          cd ministo
          docker run --rm \
            --volume "$PWD":/src \
            --user "$(id -u):$(id -g)" \
            rust-min-libc-target build --release

      - name: List built artifacts
        run: ls -lh ministo/target/release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ministo-release
          path: ministo/target/release/
