name: Build static musl binary for ministo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install musl toolchain (C & C++)
        run: |
          sudo apt update
          sudo apt install -y musl-tools g++-x86-64-linux-musl
          rustup target add x86_64-unknown-linux-musl

      - name: Build ministo with musl
        run: |
          export CC=musl-gcc
          export CXX=x86_64-linux-musl-g++
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload static binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ministo-musl
          path: target/x86_64-unknown-linux-musl/release/ministo
