name: Build Ministo with Minimal GLIBC

on:
  workflow_dispatch:    # Manual trigger
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Ministo repository
        run: git clone https://github.com/emjomi/ministo.git

      - name: Build Ministo with rust-min-libc Docker image
        run: |
          cd ministo
          docker run --rm \
            --volume "$PWD":/src \
            --user "$(id -u):$(id -g)" \
            ghcr.io/manticoresoftware/rust-min-libc:1.77.0 build --release

      - name: List build artifacts
        run: ls -lh ministo/target/release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ministo-release
          path: ministo/target/release/
